version: '3.8'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3077:8080" # Оставляем для отладки

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3050:3000" # Сайт доступен по IP:3050
    depends_on:
      - backend
